[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "price_mapping"
version = "0.0.0"
authors = [
  { name="Kevin Khang", email="kevinkhang2909@gmail.com" },
]
description = "A calculation package"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["etl"]
dependencies = [
    'tqdm',
    'pyarrow',
    'duckdb',
    'polars',
    'loguru',
    'orjson',
    'numpy',
]

[project.urls]
"Homepage" = "https://github.com/kevinkhang2909/core_tpl"
"Bug Tracker" = "https://github.com/kevinkhang2909/core_tpl/issues"
