[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "gnida"
version = "0.0.19"
authors = [
    { name="maria", email="mash.pogonina2014@yandex.ru" },
]
description = ""
readme = "README.md"
requires-python = ">=3.7.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
