# 打包配置文件
[project]
name = "aienable"
version = "0.0.0"
authors = [
  { name = "linweicheng", email = "linweicheng5@huawei-partners.com" },
]
dependencies = [
#    "opencv-python==4.8.1.78",
#    "requests==2.31.0",
]
description = "A small pakage for CV"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

