[tool.poetry]
name = "easyplot-toolbox"
version = "1.1.3"
description = "EasyplotPy is a software being developed by the research group headed by professor Wanderlei Malaquias Pereira Junior in Faculty of Engineering at Federal University of Catal√£o (UFCAT). EasyplotPy algorithm provide an easy workflow to assemble charts and save figures. The framework was developed in Python language."
authors = ["wmpjrufg <wanderlei_junior@ufcat.edu.br>", "nerodrakar <luiz_rezio@discente.ufcat.edu.br>", "mateussilva <silva_mateus@discente.ufcat.edu.br>", "nilsonjorge <nilsonjorge@discente.ufcat.edu.br>", "sfrancisco <sergio@ufcat.edu.br>"]
readme = "readme-pypi.md"

[tool.poetry.dependencies]
python = ">3.8"
matplotlib = "^3.8.4"
pandas = "^2.2.2"
seaborn = "^0.13.2"
joypy = "^0.2.6"
squarify = "^0.4.3"
numpy = ">1.23"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
