[tool.poetry]
name = "pansg"
version = "0.9.0"
description = ""
authors = ["Cao Xujie <caocao@cau.edu.cn>"]
readme = "README.md"
packages = [{include = "pansg", from = "src"}]

[tool.poetry.scripts]
pansg = 'pansg._cli:main'

[tool.poetry.dependencies]
python = "^3.9"
biopython = "^1.83"
fire = "^0.6.0"
gffutils = "^0.13"
pathlib = "^1.0.1"
matplotlib = "3.7.2"
seaborn = "^0.13.2"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
