[tool.poetry]
name = "cv_smart_house_module_motion_detection"
version = "0.1.6"
description = ""
authors = ["Mykyta Krukovskyi <mykyta.krukovskyi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
opencv-python = "^4.9.0.80"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
