[tool.poetry]
name = "ActionStreamer"
version = "0.2.1"
description = "A library for the ActionStreamer API."
authors = ["ActionStreamer <joe@actionstreamer.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
pytz = "^2024.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
