[tool.poetry]
name = "pyzas"
version = "1.0.1"
description = "PyZas!: A Python library for atomic integer operations"
license = "LGPL-3.0-only"
authors = ["Cesar Pomar <cesaralfredo.pineiro@usc.es>"]
readme = "README.md"
repository = "https://github.com/citiususc/pyzas"
keywords = ["HPC", "OMP", "OpenMP", "Multi-language", "Programming models"]
classifiers = [
    "Topic :: Software Development",
    "Topic :: Utilities"
]
build = "c_build.py"

[tool.poetry.dependencies]
python = "^3.13"

[build-system]
requires = ["poetry-core", "setuptools"]
build-backend = "poetry.core.masonry.api"
